# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
/*
  "Jinja2" = super.buildPythonPackage rec {
    pname = "Jinja2";
    version = "3.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl";
      sha256 = "0q9a30x046p3wvbgx598g4lmxwwykk0vjsjl21khx7r3zq5r7230";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "2.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6d/7c/59a3248f411813f8ccba92a55feaac4bf360d29e2ff05ee7d8e1ef2d7dbf/MarkupSafe-2.1.3.tar.gz";
      sha256 = "1bfwpdm04zswg5lgw1kvc67sp95ib0wpi0kvfhdnzs3a5p9qwndg";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
*/
  "antlr4-python3-runtime" = super.buildPythonPackage rec {
    pname = "antlr4-python3-runtime";
    version = "4.11.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/3a/4f2e9d67277cc255a17a34c1b54e02d939ca5991bc596dee3d63e587e512/antlr4_python3_runtime-4.11.1-py3-none-any.whl";
      sha256 = "0sszxi3vas4lydj3pfsdxydm9jw61iykh07m5g07546al7nm86gz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
/*
  "colorama" = super.buildPythonPackage rec {
    pname = "colorama";
    version = "0.4.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl";
      sha256 = "1ijz53xpmxds2qf02l9yf0rnp7bznwh3ci4xkw8wmh5cyn8rj7ag";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
*/
  "git-me-the-url" = super.buildPythonPackage rec {
    pname = "git-me-the-url";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/bb/5f894e0d740b6094f2fc7c3c00f9bf97eeb1778af8f8c470326f6284d716/git-me-the-url-2.1.0.tar.gz";
      sha256 = "0f60288ykf9682bs47fd0r48dq8dyikcvq15ja3gx4z31nqz9y5b";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."gitpython"
    ];
  };
/*
  "gitdb" = super.buildPythonPackage rec {
    pname = "gitdb";
    version = "4.0.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/21/a6/35f83efec687615c711fe0a09b67e58f6d1254db27b1013119de46f450bd/gitdb-4.0.10-py3-none-any.whl";
      sha256 = "1iqmhkr94m2zx40hg9jvy6dkwzwysfly9acnxmwl01i6hhlwz1n2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."smmap"
    ];
  };
  "gitpython" = super.buildPythonPackage rec {
    pname = "gitpython";
    version = "3.1.31";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/8a/d1e02cc111d65b0346f70abb83c51f8593e7134bf694a4a56d1a470caaf7/GitPython-3.1.31-py3-none-any.whl";
      sha256 = "13dyinwxxq7gnrgfzl6d0cqn7vq3fjlydqdv1jk179va9xhr6j7h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."gitdb"
    ];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "6.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/94/64287b38c7de4c90683630338cf28f129decbba0a44f0c6db35a873c73c4/importlib_metadata-6.7.0-py3-none-any.whl";
      sha256 = "1dg532flm41hhdbiizq7mbiiss6qjzg7j7n7vb2sz5wyclp0hlnb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "markdown" = super.buildPythonPackage rec {
    pname = "markdown";
    version = "3.4.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/a1/1352b0e5a3c71a79fa9265726e2217f69df9fd4de0bcb5725cc61f62a5df/Markdown-3.4.3-py3-none-any.whl";
      sha256 = "1ch80r4i9gj3b79vr547sv5ysh40xdvxv428y4jscwys4bgx8pq6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-metadata"
    ];
  };
*/
  "peakrdl" = super.buildPythonPackage rec {
    pname = "peakrdl";
    version = "0.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/de/64/7b346955c89a71feb626731efe562629ac06a1336d5d362aae33b8f79021/peakrdl-0.8.0.tar.gz";
      sha256 = "16d7jgqz3rrraxkwqrjxnn39gfnnc6n74sk855bnmz2pabna1rz1";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."peakrdl-html"
      self."peakrdl-ipxact"
      self."peakrdl-regblock"
      self."peakrdl-systemrdl"
      self."peakrdl-uvm"
      self."systemrdl-compiler"
      self."tomli"
    ];
  };
  "peakrdl-html" = super.buildPythonPackage rec {
    pname = "peakrdl-html";
    version = "2.10.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5a/dc/1b82395b9659c70ed138444d9c2d98a802fa3b56a1288d2cf00609ce1aec/peakrdl-html-2.10.1.tar.gz";
      sha256 = "071gr1m23plgdbxqhv6zbj7cwmb3qap3mpr26qlkb39hfp2v2plm";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jinja2"
      self."git-me-the-url"
      self."markdown"
      self."python-markdown-math"
      self."systemrdl-compiler"
    ];
  };
  "peakrdl-ipxact" = super.buildPythonPackage rec {
    pname = "peakrdl-ipxact";
    version = "3.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7d/00/45b3a0e3ae35d0aba004476decdae34c9b860130b7f2050e9b35be0632ba/peakrdl-ipxact-3.4.1.tar.gz";
      sha256 = "01dgg86jl1rjygcqvgpnjc2h7xk1j4d7fpx35giimzck6avz9xp7";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."systemrdl-compiler"
    ];
  };
  "peakrdl-regblock" = super.buildPythonPackage rec {
    pname = "peakrdl-regblock";
    version = "0.15.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/e6/97f7c860668fba57237a0a9abfdb7eb8ff8bb2e8f928001f303fc2a0b078/peakrdl-regblock-0.15.0.tar.gz";
      sha256 = "02xlq8lvgl9gcfbgh7w4yx1naxf9b6z9r521yfr0a32n8c41c10g";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jinja2"
      self."systemrdl-compiler"
    ];
  };
  "peakrdl-systemrdl" = super.buildPythonPackage rec {
    pname = "peakrdl-systemrdl";
    version = "0.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f1/73/bbd37e67f54a5b41ced47133f70f68e5d3aacdbd9a5747be230f4e5f5284/peakrdl-systemrdl-0.3.0.tar.gz";
      sha256 = "0zj5f2sjmgzcnvn9h7khrmp2lwxnmagf9y974c9hm4h01fvnj0x2";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."systemrdl-compiler"
    ];
  };
  "peakrdl-uvm" = super.buildPythonPackage rec {
    pname = "peakrdl-uvm";
    version = "2.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/2b/47e2a27147ae1117e9248e926a7d478b6b2e229b30fb2a0bca01870d5ebe/peakrdl-uvm-2.3.0.tar.gz";
      sha256 = "1wlwphb187nf1gw0hs8xvvijpwmplrcy43dy7vh1y86hhzya867c";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jinja2"
      self."systemrdl-compiler"
    ];
  };
  "python-markdown-math" = super.buildPythonPackage rec {
    pname = "python-markdown-math";
    version = "0.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4d/36/d16118345ff5f503d4d1c708e8427ed2213f2af7aaffac9d59010e665b5c/python_markdown_math-0.8-py3-none-any.whl";
      sha256 = "1ra18v0qia7wgw2x93r6zl3jxjnq5csynysd27lrgdmmhjfj91f6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."markdown"
    ];
  };
/*
  "smmap" = super.buildPythonPackage rec {
    pname = "smmap";
    version = "5.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6d/01/7caa71608bc29952ae09b0be63a539e50d2484bc37747797a66a60679856/smmap-5.0.0-py3-none-any.whl";
      sha256 = "150d3676rvpfb44wwmcf3pbrxc07cblmfp6y165qvrs0l3b1kfia";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
*/
  "systemrdl-compiler" = super.buildPythonPackage rec {
    pname = "systemrdl-compiler";
    version = "1.26.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/90/8d1b7f22a66d30527abb1503220c9c38b2e9f13afef3deb9bd946502c5dd/systemrdl-compiler-1.26.0.tar.gz";
      sha256 = "12mxqy9flq5sb855wxmp94d0vxnwd25lh5ivvak8ip9mdh5f515m";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."antlr4-python3-runtime"
      self."colorama"
      self."markdown"
    ];
  };
/*
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl";
      sha256 = "1k0fqfdylinb57s2aqwprahwbrsk3babg4gghz4g06hnlvky77ck";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.15.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5b/fa/c9e82bbe1af6266adf08afb563905eb87cab83fde00a0a08963510621047/zipp-3.15.0-py3-none-any.whl";
      sha256 = "0mnmg9nwhrbnb55i7d1ssi7c79f14rbxkphs2npl5rb0db3lz428";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
*/
}
